name: 🚀 Deploy Application

on:
#  push:
#    branches: [ "main" ]
#    paths-ignore:
#      - 'IaC/**'
  workflow_dispatch:
#  workflow_run:
#    workflows: [ "🏗 Deploy Infrastructure" ]
#    types:
#      - completed
#    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0.x'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: '${{ vars.AZURE_WEBAPP_NAME }}-${{ vars.AZURE_WEBAPP_ENVIRONMENT }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
