name: 🏗️ Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
    paths:
      - 'IaC/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        uses: Azure/bicep-deploy@v2.2.0
        with:
          type: 'deployment'
          operation: 'create'
          name: 'webapp-deployment'
          scope: 'resourceGroup'
          template-file: './IaC/main.bicep'
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ vars.AZURE_RESOURCE_GROUP }}
          parameters: |
            webAppName: ${{ vars.AZURE_WEBAPP_NAME }}
            environmentName: ${{ vars.AZURE_WEBAPP_ENVIRONMENT }}
            sqlAdminLogin: ${{ secrets.SQL_ADMIN_LOGIN }}
            sqlAdminPassword: ${{ secrets.SQL_ADMIN_PASSWORD }}
            
      - name: Results
        run: |
          echo "Web App URL: ${{ steps.deploy.outputs.appUrl }}"
          echo "App Name: ${{ steps.deploy.outputs.appName }}"
          echo "SQL Server: ${{ steps.deploy.outputs.sqlServerName }}"
          echo "Database: ${{ steps.deploy.outputs.sqlDatabaseName }}"

