# This workflow handles application deployments.
# It runs in three scenarios:
# 1. After successful infrastructure deployments (via workflow_run trigger)
# 2. On direct application changes (excluding IaC/** files)
# 3. When manually triggered via workflow_dispatch
#
# The workflow_run trigger ensures this workflow waits for any infrastructure
# deployments to complete successfully before running. This maintains a safe
# deployment order where infrastructure changes are always applied first.

name: 🚀 Deploy Application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'IaC/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ "🏗 Deploy Infrastructure" ]
    types:
      - completed
    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0.x'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: '${{ vars.AZURE_WEBAPP_NAME }}-${{ vars.AZURE_WEBAPP_ENVIRONMENT }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
